timer:
    default_work_duration: 45m0s
    default_break_duration: 5m0s
    default_long_break_duration: 15m0s
    auto_start_breaks: false
notifications:
    enabled: true
    sound: false
    message: Timer completed!
plugins:
    directory: /home/ritchie/.config/pomodux/plugins
    enabled:
        kimai: false
pluginsraw: {}
logging:
    level: debug
    format: text
    output: file
    log_file: "/home/ritchie/.local/share/pomodux/pomodux.log"
    show_caller: false
