---
notes:
  folder: '~/Nextcloud/Journal/Inbox'
  one_on_one:
    resource_folders: '~/Nextcloud/ICBC/Resources'
    url: 'https://rpa.macapinlac.network/webhook/c78c6222-a883-4685-913e-a1652cb7a82b'
journal:
  inbox: '~/Nextcloud/Journal/Inbox'
  base_folder: '~/Nextcloud/Journal'

